In [29]:
import json
import pandas as pd 
from pathlib import Path

In [2]:
f_wb_sch = '/Users/jacquelinewong/Documents/GitHub/YOLO/ref/workbook_schema.json'
f_sch_gis = '/Users/jacquelinewong/Documents/GitHub/YOLO/ref/schema_Group_income_statement.json'

with open(f_wb_sch, 'r') as f:
    sch_wb = json.load(f)

sch_wb.keys()

dict_keys(['workbook', 'total_sheets', 'processed_sheets', 'all_sheet_names', 'sheets'])

In [5]:
sch_wb['sheets'][2].keys()

dict_keys(['sheet_type', 'dimensions', 'merged_ranges', 'column_headers', 'data_start_row', 'sections', 'footnotes', 'sheet'])

In [11]:
for k, v in sch_wb['sheets'][2].items():
    print(k)
    print(v)
    print()

sheet_type
semi_structured

dimensions
{'rows': 90, 'cols': 19}

merged_ranges
['A90:I90', 'B5:F5', 'H5:I5', 'B53:F53', 'H53:I53', 'B65:F65', 'H65:I65']

column_headers
{'0': 'HSBC / HSBC Holdings plc consolidated income statement', '1': 'Quarter ended', '7': 'Year to date'}

data_start_row
5

sections
[{'label': '', 'role': 'section_header', 'bold': False, 'indent': 0, 'outline_level': 0, 'children': [{'label': 'Reported ($m)', 'role': 'subtotal', 'bold': True, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 46022.0, 'col_2': 45930.0, 'col_3': 45838.0, 'col_4': 45747.0}}, {'label': 'Net interest income', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 9196.0, 'col_2': 8777.0, 'col_3': 8519.0, 'col_4': 8302.0}}, {'label': 'Net fee income', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 3194.0, 'col_2': 3506.0, 'col_3': 3319.0, 'col_4': 3324.0}}, {'label': 'Other operating income', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 3974.0, 'col_2': 5505.0, 'col_3': 4635.0, 'col_4': 6023.0}}, {'label': "Net operating income before change in expected credit losses and other credit impairment charges ('Revenue')", 'role': 'subtotal', 'bold': True, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 16364.0, 'col_2': 17788.0, 'col_3': 16473.0, 'col_4': 17649.0}}, {'label': "Change in expected credit losses and other credit impairment charges ('ECL')", 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -901.0, 'col_2': -1008.0, 'col_3': -1065.0, 'col_4': -876.0}}, {'label': 'Total operating expenses', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -9330.0, 'col_2': -10076.0, 'col_3': -8920.0, 'col_4': -8102.0}}, {'label': 'Share of profit in associates and joint ventures less impairment', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 669.0, 'col_2': 591.0, 'col_3': -162.0, 'col_4': 813.0}}, {'label': 'Profit/(loss) before tax', 'role': 'subtotal', 'bold': True, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 6802.0, 'col_2': 7295.0, 'col_3': 6326.0, 'col_4': 9484.0}}, {'label': 'Tax credit/(charge)', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -1615.0, 'col_2': -1792.0, 'col_3': -1455.0, 'col_4': -1914.0}}, {'label': 'Profit/(loss) after tax', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 5187.0, 'col_2': 5503.0, 'col_3': 4871.0, 'col_4': 7570.0}}, {'label': 'Profit/(loss) attributable to:', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {}}, {'label': "- ordinary shareholders of the parent company ('PAOS')", 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 4719.0, 'col_2': 4873.0, 'col_3': 4578.0, 'col_4': 6932.0}}, {'label': '- other equity holders of the parent company', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 225.0, 'col_2': 411.0, 'col_3': 155.0, 'col_4': 392.0}}, {'label': '- non-controlling interests', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 243.0, 'col_2': 219.0, 'col_3': 138.0, 'col_4': 246.0}}, {'label': 'Impairment of goodwill and other intangible assets (net of tax)', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 80.0, 'col_2': 40.0, 'col_3': 24.0, 'col_4': 0.0}}, {'label': 'PAOS net of goodwill impairment', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 4799.0, 'col_2': 4913.0, 'col_3': 4602.0, 'col_4': 6932.0}}]}, {'label': 'Constant currency  ($m)', 'role': 'section_header', 'bold': True, 'font_size': 9.0, 'indent': 0, 'outline_level': 0, 'children': [{'label': 'Revenue', 'role': 'subtotal', 'bold': True, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 16364.0, 'col_2': 17722.0, 'col_3': 16472.0, 'col_4': 18201.0}}, {'label': 'ECL', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -901.0, 'col_2': -1010.0, 'col_3': -1079.0, 'col_4': -913.0}}, {'label': 'Total operating expenses', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -9330.0, 'col_2': -10015.0, 'col_3': -8956.0, 'col_4': -8383.0}}, {'label': 'Share of profit in associates and joint ventures less impairment', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 669.0, 'col_2': 594.0, 'col_3': -171.0, 'col_4': 829.0}}, {'label': 'Profit/(loss) before tax', 'role': 'subtotal', 'bold': True, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 6802.0, 'col_2': 7291.0, 'col_3': 6266.0, 'col_4': 9734.0}}, {'label': 'Constant currency revenue excluding notable items', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 17723.0, 'col_2': 17834.0, 'col_3': 17677.0, 'col_4': 18293.0}}, {'label': 'Constant currency profit before tax excluding notable items', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 8586.0, 'col_2': 9077.0, 'col_3': 9148.0, 'col_4': 10027.0}}]}, {'label': 'Notable items (reported) ($m)', 'role': 'section_header', 'bold': True, 'font_size': 9.0, 'indent': 0, 'outline_level': 0, 'children': []}, {'label': 'Notable items', 'role': 'section_header', 'bold': True, 'font_size': 9.0, 'indent': 0, 'outline_level': 0, 'children': [{'label': 'Revenue', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -1359.0, 'col_2': -112.0, 'col_3': -1184.0, 'col_4': -91.0}}, {'label': 'of which: Banking net interest income', 'role': 'line_item', 'bold': False, 'indent': 1, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.0, 'col_2': 0.0, 'col_3': 0.0, 'col_4': 0.0}}, {'label': 'of which: Fee and other income', 'role': 'line_item', 'bold': False, 'indent': 1, 'outline_level': 0, 'sample_values': {'Quarter ended': -1359.0, 'col_2': -112.0, 'col_3': -1184.0, 'col_4': -91.0}}, {'label': 'ECL', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.0, 'col_2': 0.0, 'col_3': 0.0, 'col_4': 0.0}}, {'label': 'Operating expenses', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -425.0, 'col_2': -1696.0, 'col_3': -652.0, 'col_4': -191.0}}, {'label': 'Impairment losses of interest in BoCom associate', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.0, 'col_2': 0.0, 'col_3': -1000.0, 'col_4': 0.0}}]}, {'label': 'Notable items (constant currency) ($m)', 'role': 'section_header', 'bold': True, 'font_size': 9.0, 'indent': 0, 'outline_level': 0, 'children': []}, {'label': 'Notable items', 'role': 'section_header', 'bold': True, 'font_size': 9.0, 'indent': 0, 'outline_level': 0, 'children': [{'label': 'Revenue', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -1359.0, 'col_2': -112.0, 'col_3': -1205.0, 'col_4': -92.0}}, {'label': 'of which: Banking net interest income', 'role': 'line_item', 'bold': False, 'indent': 1, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.0, 'col_2': 0.0, 'col_3': 0.0, 'col_4': 0.0}}, {'label': 'of which: Fee and other income', 'role': 'line_item', 'bold': False, 'indent': 1, 'outline_level': 0, 'sample_values': {'Quarter ended': -1359.0, 'col_2': -112.0, 'col_3': -1205.0, 'col_4': -92.0}}, {'label': 'ECL', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.0, 'col_2': 0.0, 'col_3': 0.0, 'col_4': 0.0}}, {'label': 'Operating expenses', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -425.0, 'col_2': -1674.0, 'col_3': -656.0, 'col_4': -201.0}}, {'label': 'Impairment losses of interest in BoCom associate', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.0, 'col_2': 0.0, 'col_3': -1021.0, 'col_4': 0.0}}, {'label': 'Earnings metrics', 'role': 'subtotal', 'bold': True, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 46022.0, 'col_2': 45930.0, 'col_3': 45838.0, 'col_4': 45747.0}}, {'label': 'Return on average equity (annualised)', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.10800000000000001, 'col_2': 0.113, 'col_3': 0.107, 'col_4': 0.166}}, {'label': 'Return on average tangible equity (annualised)', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.11800000000000001, 'col_2': 0.12300000000000001, 'col_3': 0.115, 'col_4': 0.179}}, {'label': 'Return on average tangible equity excluding notable items (annualised)1', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.159, 'col_2': 0.166, 'col_3': 0.17800000000000002, 'col_4': 0.184}}, {'label': 'Earnings per share ($)', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.28, 'col_2': 0.28, 'col_3': 0.26, 'col_4': 0.39}}, {'label': 'Earnings per share excluding material notable items and related impacts ($)', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.37, 'col_2': 0.36, 'col_3': 0.39, 'col_4': 0.39}}, {'label': 'Constant currency ECL / average gross loans (annualised)', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.0036, 'col_2': 0.004, 'col_3': 0.0044, 'col_4': 0.0038}}]}, {'label': 'Dividends', 'role': 'section_header', 'bold': True, 'font_size': 9.0, 'indent': 0, 'outline_level': 0, 'children': [{'label': 'Dividends per share - declared in respect of the period ($)', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.45, 'col_2': 0.1, 'col_3': 0.1, 'col_4': 0.1}}, {'label': 'Revenue notable items ($m)', 'role': 'subtotal', 'bold': True, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 46022.0, 'col_2': 45930.0, 'col_3': 45838.0, 'col_4': 45747.0}}, {'label': 'Total', 'role': 'subtotal', 'bold': True, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -1359.0, 'col_2': -112.0, 'col_3': -1184.0, 'col_4': -91.0}}, {'label': '– Disposals, wind-downs, acquisitions and related costs', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -1359.0, 'col_2': -144.0, 'col_3': -48.0, 'col_4': -91.0}}, {'label': '– Early redemption of legacy securities', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.0, 'col_2': 0.0, 'col_3': 0.0, 'col_4': 0.0}}, {'label': '– Dilution loss of interest in BoCom associate', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.0, 'col_2': 32.0, 'col_3': -1136.0, 'col_4': 0.0}}]}, {'label': 'Cost notable items ($m)', 'role': 'section_header', 'bold': True, 'font_size': 9.0, 'indent': 0, 'outline_level': 0, 'children': [{'label': 'Total', 'role': 'subtotal', 'bold': True, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -425.0, 'col_2': -1696.0, 'col_3': -652.0, 'col_4': -191.0}}, {'label': '– Disposals, wind-downs, acquisitions and related costs', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -157.0, 'col_2': -118.0, 'col_3': -177.0, 'col_4': -50.0}}, {'label': '– Restructuring and other related costs', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -257.0, 'col_2': -157.0, 'col_3': -475.0, 'col_4': -141.0}}, {'label': '– Legal provision', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': -11.0, 'col_2': -1421.0, 'col_3': 0.0, 'col_4': 0.0}}, {'label': 'Impairment losses of interest in BoCom associate ($m)', 'role': 'subtotal', 'bold': True, 'indent': 0, 'outline_level': 0, 'sample_values': {'Quarter ended': 0.0, 'col_2': 0.0, 'col_3': -1000.0, 'col_4': 0.0}}, {'label': '1 We have revised the adjustments made to average tangible equity for the purposes of computing our return on average tangible equity (‘RoTE’) excluding notable items measure. Prior to this, we adjusted average tangible equity for the average impact of notable items whereas from 2025 we no longer make adjustments to average tangible equity. Comparatives have been re-presented on the revised basis.', 'role': 'line_item', 'bold': False, 'indent': 0, 'outline_level': 0, 'sample_values': {}}]}]

footnotes
['1 We have revised the adjustments made to average tangible equity for the purposes of computing our return on average tangible equity (‘RoTE’) excluding notable items measure. Prior to this, we adjusted average tangible equity for the average impact of notable items whereas from 2025 we no longer make adjustments to average tangible equity. Comparatives have been re-presented on the revised basis.']

sheet
Group income statement

In [9]:
len(sch_wb['sheets'][2]['sections'])

8

In [12]:
sch_wb['sheets'][2]['sections'][0].keys()

dict_keys(['label', 'role', 'bold', 'indent', 'outline_level', 'children'])

In [13]:
sch_wb['sheets'][2]['sections'][0]

{'label': '',
 'role': 'section_header',
 'bold': False,
 'indent': 0,
 'outline_level': 0,
 'children': [{'label': 'Reported ($m)',
   'role': 'subtotal',
   'bold': True,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 46022.0,
    'col_2': 45930.0,
    'col_3': 45838.0,
    'col_4': 45747.0}},
  {'label': 'Net interest income',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 9196.0,
    'col_2': 8777.0,
    'col_3': 8519.0,
    'col_4': 8302.0}},
  {'label': 'Net fee income',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 3194.0,
    'col_2': 3506.0,
    'col_3': 3319.0,
    'col_4': 3324.0}},
  {'label': 'Other operating income',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 3974.0,
    'col_2': 5505.0,
    'col_3': 4635.0,
    'col_4': 6023.0}},
  {'label': "Net operating income before change in expected credit losses and other credit impairment charges ('Revenue')",
   'role': 'subtotal',
   'bold': True,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 16364.0,
    'col_2': 17788.0,
    'col_3': 16473.0,
    'col_4': 17649.0}},
  {'label': "Change in expected credit losses and other credit impairment charges ('ECL')",
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': -901.0,
    'col_2': -1008.0,
    'col_3': -1065.0,
    'col_4': -876.0}},
  {'label': 'Total operating expenses',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': -9330.0,
    'col_2': -10076.0,
    'col_3': -8920.0,
    'col_4': -8102.0}},
  {'label': 'Share of profit in associates and joint ventures less impairment',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 669.0,
    'col_2': 591.0,
    'col_3': -162.0,
    'col_4': 813.0}},
  {'label': 'Profit/(loss) before tax',
   'role': 'subtotal',
   'bold': True,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 6802.0,
    'col_2': 7295.0,
    'col_3': 6326.0,
    'col_4': 9484.0}},
  {'label': 'Tax credit/(charge)',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': -1615.0,
    'col_2': -1792.0,
    'col_3': -1455.0,
    'col_4': -1914.0}},
  {'label': 'Profit/(loss) after tax',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 5187.0,
    'col_2': 5503.0,
    'col_3': 4871.0,
    'col_4': 7570.0}},
  {'label': 'Profit/(loss) attributable to:',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {}},
  {'label': "- ordinary shareholders of the parent company ('PAOS')",
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 4719.0,
    'col_2': 4873.0,
    'col_3': 4578.0,
    'col_4': 6932.0}},
  {'label': '- other equity holders of the parent company',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 225.0,
    'col_2': 411.0,
    'col_3': 155.0,
    'col_4': 392.0}},
  {'label': '- non-controlling interests',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 243.0,
    'col_2': 219.0,
    'col_3': 138.0,
    'col_4': 246.0}},
  {'label': 'Impairment of goodwill and other intangible assets (net of tax)',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 80.0,
    'col_2': 40.0,
    'col_3': 24.0,
    'col_4': 0.0}},
  {'label': 'PAOS net of goodwill impairment',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Quarter ended': 4799.0,
    'col_2': 4913.0,
    'col_3': 4602.0,
    'col_4': 6932.0}}]}

In [14]:
f_cr = '/Users/jacquelinewong/Documents/GitHub/YOLO/test-generator.json'
with open(f_cr, 'r') as f:
    cr = json.load(f)

cr.keys()

dict_keys(['workbook', 'total_sheets', 'processed_sheets', 'all_sheet_names', 'sheets'])

In [17]:
cr['total_sheets']

21

In [22]:
cr['all_sheet_names']

['Cover - Notice',
 'Cover - Index',
 'Group income statement',
 'Group balance sheet',
 'Group MVOI',
 'Group NIM',
 'Hong Kong business',
 'UK business',
 'CIB business',
 'IWPB business',
 'Corporate Centre',
 'HBUK',
 'HCIB',
 'HBAP (consol)',
 'HBAP (HK)',
 'HNAH',
 'HBCA',
 'Grupo Financiero (Mexico)',
 'HBME',
 'Other trading entities',
 'Credit risk']

In [25]:
cr['sheets'][0].keys()

dict_keys(['sheet_type', 'dimensions', 'merged_ranges', 'column_headers', 'data_start_row', 'sections', 'footnotes', 'sheet'])

In [27]:
len(cr['sheets'][0]['sections'])

7

In [28]:
cr['sheets'][0]['sections'][0]

{'label': '',
 'role': 'section_header',
 'bold': False,
 'indent': 0,
 'outline_level': 0,
 'children': [{'label': 'Loans and advances to customers at amortised cost',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 893433.0,
    'Stage 2 / $m': 80936.0,
    'Stage 3 / $m': 24389.0,
    'POCI2 / $m': 333.0}},
  {'label': '– personal',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 446696.0,
    'Stage 2 / $m': 23887.0,
    'Stage 3 / $m': 3945.0,
    'POCI2 / $m': 0.0}},
  {'label': '– corporate and commercial',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 349763.0,
    'Stage 2 / $m': 54636.0,
    'Stage 3 / $m': 19966.0,
    'POCI2 / $m': 140.0}},
  {'label': '– non-bank financial institutions',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 96974.0,
    'Stage 2 / $m': 2413.0,
    'Stage 3 / $m': 478.0,
    'POCI2 / $m': 193.0}},
  {'label': 'Loans and advances to banks at amortised cost',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 108336.0,
    'Stage 2 / $m': 132.0,
    'Stage 3 / $m': 1.0,
    'POCI2 / $m': 0.0}},
  {'label': 'Other financial assets measured at amortised cost',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 888491.0,
    'Stage 2 / $m': 1651.0,
    'Stage 3 / $m': 184.0,
    'POCI2 / $m': 0.0}},
  {'label': 'Loans and other credit-related commitments',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 669648.0,
    'Stage 2 / $m': 20488.0,
    'Stage 3 / $m': 652.0,
    'POCI2 / $m': 4.0}},
  {'label': '– personal',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 270494.0,
    'Stage 2 / $m': 1945.0,
    'Stage 3 / $m': 92.0,
    'POCI2 / $m': 0.0}},
  {'label': '– corporate and commercial',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 255740.0,
    'Stage 2 / $m': 14649.0,
    'Stage 3 / $m': 560.0,
    'POCI2 / $m': 4.0}},
  {'label': '– financial',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 143414.0,
    'Stage 2 / $m': 3894.0,
    'Stage 3 / $m': 0.0,
    'POCI2 / $m': 0.0}},
  {'label': 'Financial guarantees',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 15913.0,
    'Stage 2 / $m': 1371.0,
    'Stage 3 / $m': 192.0,
    'POCI2 / $m': 0.0}},
  {'label': '– personal',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 1446.0,
    'Stage 2 / $m': 0.0,
    'Stage 3 / $m': 0.0,
    'POCI2 / $m': 0.0}},
  {'label': '– corporate and commercial',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 10071.0,
    'Stage 2 / $m': 1287.0,
    'Stage 3 / $m': 190.0,
    'POCI2 / $m': 0.0}},
  {'label': '– financial',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 4396.0,
    'Stage 2 / $m': 84.0,
    'Stage 3 / $m': 2.0,
    'POCI2 / $m': 0.0}},
  {'label': 'At 31 December 2025',
   'role': 'subtotal',
   'bold': True,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {'Gross carrying/nominal amount1 / Stage 1 / $m': 2575821.0,
    'Stage 2 / $m': 104578.0,
    'Stage 3 / $m': 25418.0,
    'POCI2 / $m': 337.0}},
  {'label': '1 Represents the maximum amount at risk should the contracts be fully drawn upon and clients default.',
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {}},
  {'label': "2 Purchased or originated credit impaired ('POCI').",
   'role': 'line_item',
   'bold': False,
   'indent': 0,
   'outline_level': 0,
   'sample_values': {}}]}

In [38]:
dir = Path('/Users/jacquelinewong/Documents/GitHub/YOLO/data/op_csv/credit_risk')
# List all CSV files in the directory
csv_files = list(dir.glob('*.csv'))
for f in csv_files:
    print(f.name)

corporate_and_commercial.csv
by_legal_entity_2.csv
total_wholesale_lending_for_loans_and_advances_to_banks_and_customers_by_stage_distribution.csv
total_personal_lending_for_loans_and_advances_to_customers_by_stage_distribution.csv
stage_2_days_past_due_analysis_at_31_december_2025.csv
by_legal_entity.csv
section_01.csv

In [39]:
df = pd.read_csv(dir / 'total_wholesale_lending_for_loans_and_advances_to_banks_and_customers_by_stage_distribution.csv')
df

,excel_row,table_id,role,indent,outline_level,label,Gross carrying amount / Stage 1 / $m,Stage 2 / $m,Stage 3 / $m,POCI / $m,Total / $m,Allowance for ECL / Stage 1 / $m,Stage 2 / $m__2,Stage 3 / $m__2,POCI / $m__2,Total / $m__2
0,77,4,line_item,0,0,Corporate and commercial,349763,54636,19966,140,424505,-478,-1064,-5909,-75,-7526
1,78,4,line_item,0,0,"– agriculture, forestry and fishing",6179,1058,355,0,7592,-11,-26,-60,0,-97
2,79,4,line_item,0,0,– mining and quarrying,6109,747,126,0,6982,-6,-10,-70,0,-86
3,80,4,line_item,0,0,– manufacturing,74321,9785,2229,37,86372,-87,-132,-720,-21,-960
4,81,4,line_item,0,0,"– electricity, gas, steam and air-conditioning...",18020,1096,206,0,19322,-19,-22,-85,0,-126
5,82,4,line_item,0,0,"– water supply, sewerage, waste management and...",2319,132,112,0,2563,-3,-2,-36,0,-41
6,83,4,line_item,0,0,– real estate and construction,56041,21222,10497,92,87852,-84,-449,-2679,-51,-3263
7,84,4,line_item,1,0,– of which: commercial real estate,41893,18183,9175,87,69338,-65,-384,-2116,-45,-2610
8,86,4,line_item,0,0,"– wholesale and retail trade, repair of motor ...",74621,7387,2538,11,84557,-69,-92,-1123,-3,-1287
9,87,4,line_item,0,0,– transportation and storage,16594,3818,307,0,20719,-17,-82,-75,0,-174
10,88,4,line_item,0,0,– accommodation and food,10881,2072,1436,0,14389,-31,-65,-303,0,-399
11,89,4,line_item,0,0,"– publishing, audiovisual and broadcasting",22860,2110,377,0,25347,-52,-38,-108,0,-198
12,91,4,line_item,0,0,"– professional, scientific and technical activ...",22580,1923,520,0,25023,-29,-36,-153,0,-218
13,92,4,line_item,0,0,– administrative and support services,16962,1993,570,0,19525,-21,-53,-321,0,-395
14,93,4,line_item,0,0,"– public administration and defence, compulsor...",64,0,0,0,64,0,0,0,0,0
15,94,4,line_item,0,0,– education,1975,244,40,0,2259,-5,-10,-11,0,-26
16,95,4,line_item,0,0,– health and care,3982,323,98,0,4403,-7,-11,-14,0,-32
17,96,4,line_item,0,0,"– arts, entertainment and recreation",2074,116,123,0,2313,-4,-5,-42,0,-51
18,97,4,line_item,0,0,– other services,5764,524,311,0,6599,-31,-31,-106,0,-168
19,98,4,line_item,0,0,– activities of households,835,6,0,0,841,0,0,0,0,0
20,99,4,line_item,0,0,– extra-territorial organisations and bodies a...,164,0,0,0,164,0,0,0,0,0
21,100,4,line_item,0,0,– government,7418,80,121,0,7619,-2,0,-3,0,-5
22,101,4,line_item,0,0,– asset-backed securities,0,0,0,0,0,0,0,0,0,0
23,102,4,line_item,0,0,Non-bank financial institutions,96974,2413,478,193,100058,-56,-19,-293,-1,-369
24,103,4,line_item,0,0,Loans and advances to banks,108336,132,1,0,108469,-4,-2,-1,0,-7
25,104,4,subtotal,0,0,At 31 December 2025,555073,57181,20445,333,633032,-538,-1085,-6203,-76,-7902

In [40]:
df = pd.read_csv(dir / 'total_personal_lending_for_loans_and_advances_to_customers_by_stage_distribution.csv')
df

,excel_row,table_id,role,indent,outline_level,label,Gross carrying amount / Stage 1 / $m,Stage 2 / $m,Stage 3 / $m,Total / $m,Allowance for ECL / Stage 1 / $m,Stage 2 / $m__2,Stage 3 / $m__2,Total / $m__2
0,52,3,line_item,0,0,First lien residential mortgages,365498,18148,2655,386301,-58,-109,-313,-480
1,53,3,line_item,0,0,Credit cards,22781,3260,373,26414,-339,-731,-231,-1301
2,54,3,line_item,0,0,Other personal lending,58417,2479,917,61813,-270,-395,-351,-1016
3,55,3,line_item,0,0,– other personal lending which is secured1,39906,517,270,40693,-24,-19,-65,-108
4,56,3,line_item,0,0,– other personal lending which is unsecured,18511,1962,647,21120,-246,-376,-286,-908
5,57,3,subtotal,0,0,At 31 December 2025,446696,23887,3945,474528,-667,-1235,-895,-2797